"""DB2 database adapter for the migration toolkit.

Connects via ``ibm_db`` / ``ibm_db_dbi`` (PEP 249) and discovers schema
metadata from DB2's SYSCAT catalog views.

DSN formats accepted
--------------------
* Full connection string::

      DATABASE=mydb;HOSTNAME=host;PORT=60000;PROTOCOL=TCPIP;UID=user;PWD=pass

* Simplified ``user:pass@host:port/dbname`` which is parsed and expanded.

Identity handling
-----------------
DB2 identity columns have a *generation* attribute:

* ``GENERATED ALWAYS``  (``GENERATED = 'A'``) — explicit INSERT of the
  identity value fails with SQLSTATE 428C9.  The adapter works around this
  by temporarily ``ALTER``-ing the column to ``BY DEFAULT`` for the duration
  of the insert batch, then restoring it.
* ``GENERATED BY DEFAULT`` (``GENERATED = 'D'``) — explicit INSERT works
  without intervention.

A preferred bulk-load path via the DB2 ``LOAD`` utility with
``IDENTITYOVERRIDE`` is also provided (requires ``db2`` CLI access on the
host).

Registration
------------
::

    from dbmigrate.database.db2 import DB2Adapter  # auto-registers
"""

from __future__ import annotations

import logging
import re
import subprocess
import tempfile
from contextlib import contextmanager
from typing import Any, Generator, Optional

import ibm_db  # type: ignore[import-untyped]
import ibm_db_dbi  # type: ignore[import-untyped]

from dbmigrate.database import Database, register_adapter
from dbmigrate.models import (
    ColumnMetadata,
    ForeignKeyMetadata,
    IdentityStrategy,
    PrimaryKeyMetadata,
    SequenceMetadata,
    TriggerMetadata,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# DSN parsing helper
# ---------------------------------------------------------------------------

_SIMPLE_DSN_RE = re.compile(
    r"^(?P<user>[^:]+):(?P<password>[^@]+)@(?P<host>[^:]+):(?P<port>\d+)/(?P<database>.+)$"
)


def _normalise_dsn(dsn: str) -> str:
    """Convert a simplified DSN into the full IBM connection string.

    If the DSN already contains ``DATABASE=`` it is returned unchanged.
    """
    if "DATABASE=" in dsn.upper():
        return dsn
    m = _SIMPLE_DSN_RE.match(dsn)
    if not m:
        raise ValueError(
            "DSN must be either 'user:pass@host:port/dbname' or a full "
            "IBM connection string (DATABASE=...;HOSTNAME=...;...)."
        )
    return (
        f"DATABASE={m['database']};HOSTNAME={m['host']};PORT={m['port']};"
        f"PROTOCOL=TCPIP;UID={m['user']};PWD={m['password']}"
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _uc(name: str) -> str:
    """Uppercase a name for use in DB2 SQL and catalog queries."""
    return name.upper()


def _lc(name: str) -> str:
    """Lowercase a name for internal storage."""
    return name.lower()


# DB2 SYSCAT.COLUMNS.IDENTITY values
_IDENTITY_YES = "Y"

# DB2 SYSCAT.COLUMNS.GENERATED values
_GEN_ALWAYS = "A"
_GEN_BY_DEFAULT = "D"

# DB2 trigger event codes
_TRIG_EVENT_MAP = {"I": "INSERT", "U": "UPDATE", "D": "DELETE"}
_TRIG_TIME_MAP = {"B": "BEFORE", "A": "AFTER"}

# Default fetch size for streaming
_DEFAULT_FETCH_SIZE = 5000


# ---------------------------------------------------------------------------
# Adapter
# ---------------------------------------------------------------------------


@register_adapter("db2")
class DB2Adapter(Database):
    """IBM DB2 adapter using ``ibm_db`` / ``ibm_db_dbi``.

    Parameters
    ----------
    dsn:
        Connection string (full or simplified).
    schema:
        DB2 schema name.  Stored lowercase internally; uppercased for SQL.
    use_load_utility:
        When ``True``, :meth:`bulk_load` uses the ``db2 LOAD`` CLI.
        When ``False`` (default), it uses the ``ALTER COLUMN`` identity
        override approach.
    """

    def __init__(
        self,
        dsn: str,
        schema: str,
        *,
        use_load_utility: bool = False,
    ) -> None:
        super().__init__(dsn, schema)
        self._raw_dsn = _normalise_dsn(dsn)
        self._ibm_conn: Any = None  # low-level ibm_db connection handle
        self._dbi_conn: Optional[ibm_db_dbi.Connection] = None
        self._use_load_utility = use_load_utility

    # ---- properties -------------------------------------------------------

    @property
    def engine_name(self) -> str:  # type: ignore[override]
        return "DB2"

    # ---- connection lifecycle ---------------------------------------------

    def connect(self) -> None:
        """Establish both low-level (``ibm_db``) and PEP 249 connections."""
        if self._dbi_conn is not None:
            return  # already connected
        logger.info("Connecting to DB2: %s", re.sub(r"PWD=[^;]+", "PWD=***", self._raw_dsn))
        try:
            self._ibm_conn = ibm_db.connect(self._raw_dsn, "", "")
            # Disable autocommit so we control transactions explicitly.
            ibm_db.autocommit(self._ibm_conn, ibm_db.SQL_AUTOCOMMIT_OFF)
            # Wrap in PEP 249 interface for cursor-based access.
            self._dbi_conn = ibm_db_dbi.Connection(self._ibm_conn)
            logger.info("DB2 connection established.")
        except Exception as exc:
            self._ibm_conn = None
            self._dbi_conn = None
            raise ConnectionError(f"Failed to connect to DB2: {exc}") from exc

    def close(self) -> None:
        """Close both connections."""
        if self._dbi_conn is not None:
            try:
                self._dbi_conn.close()
            except Exception:
                pass
            self._dbi_conn = None
        if self._ibm_conn is not None:
            try:
                ibm_db.close(self._ibm_conn)
            except Exception:
                pass
            self._ibm_conn = None
        logger.info("DB2 connection closed.")

    def _ensure_connected(self) -> ibm_db_dbi.Connection:
        if self._dbi_conn is None:
            raise RuntimeError("Not connected — call connect() first.")
        return self._dbi_conn

    # ---- transaction management -------------------------------------------

    def begin_transaction(self) -> None:
        """DB2 with autocommit off is already in an implicit transaction.

        This is a no-op; the transaction began after the last commit/rollback.
        """
        logger.debug("begin_transaction (implicit — autocommit is off)")

    def commit(self) -> None:
        conn = self._ensure_connected()
        conn.commit()
        logger.debug("Transaction committed.")

    def rollback_transaction(self) -> None:
        conn = self._ensure_connected()
        conn.rollback()
        logger.debug("Transaction rolled back.")

    # ---- utility ----------------------------------------------------------

    def execute(self, sql: str, params: Optional[tuple[Any, ...]] = None) -> Any:
        """Execute a single statement and return the cursor."""
        conn = self._ensure_connected()
        cursor = conn.cursor()
        try:
            if params:
                cursor.execute(sql, params)
            else:
                cursor.execute(sql)
            return cursor
        except Exception:
            cursor.close()
            raise

    def execute_many(self, sql: str, params_list: list[tuple[Any, ...]]) -> int:
        """Execute *sql* for each parameter tuple.  Returns total affected rows."""
        conn = self._ensure_connected()
        cursor = conn.cursor()
        total = 0
        try:
            for params in params_list:
                cursor.execute(sql, params)
                total += cursor.rowcount if cursor.rowcount > 0 else 0
            return total
        finally:
            cursor.close()

    def get_version(self) -> str:
        """Return the DB2 version string from ``SYSIBM.SYSDUMMY1``."""
        cursor = self.execute(
            "SELECT SERVICE_LEVEL FROM TABLE(SYSPROC.ENV_GET_INST_INFO()) AS X"
        )
        row = cursor.fetchone()
        cursor.close()
        if row:
            return str(row[0]).strip()
        # fallback
        cursor = self.execute("SELECT GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1")
        row = cursor.fetchone()
        cursor.close()
        return str(row[0]).strip() if row else "unknown"

    def get_encoding(self) -> Optional[str]:
        """Return the database code page."""
        try:
            cursor = self.execute(
                "SELECT CODEPAGE FROM SYSCAT.DATATYPES WHERE TYPENAME = 'VARCHAR' "
                "FETCH FIRST 1 ROWS ONLY"
            )
            row = cursor.fetchone()
            cursor.close()
            return str(row[0]) if row else None
        except Exception:
            return None

    # ---- schema discovery -------------------------------------------------

    def get_tables(self) -> list[str]:
        """Return user table names from ``SYSCAT.TABLES``."""
        cursor = self.execute(
            "SELECT TABNAME FROM SYSCAT.TABLES "
            "WHERE TABSCHEMA = ? AND TYPE = 'T' "
            "ORDER BY TABNAME",
            (_uc(self.schema),),
        )
        tables = [_lc(row[0]) for row in cursor.fetchall()]
        cursor.close()
        logger.debug("Discovered %d tables in schema %s.", len(tables), self.schema)
        return tables

    def get_columns(self, table_name: str) -> list[ColumnMetadata]:
        """Return column metadata from ``SYSCAT.COLUMNS``."""
        cursor = self.execute(
            "SELECT COLNAME, TYPENAME, LENGTH, SCALE, NULLS, IDENTITY, "
            "       GENERATED, DEFAULT, COLNO "
            "FROM SYSCAT.COLUMNS "
            "WHERE TABSCHEMA = ? AND TABNAME = ? "
            "ORDER BY COLNO",
            (_uc(self.schema), _uc(table_name)),
        )
        columns: list[ColumnMetadata] = []
        for row in cursor.fetchall():
            (
                colname, typename, length, scale, nulls,
                identity, generated, default_val, colno,
            ) = row

            is_identity = identity == _IDENTITY_YES
            identity_gen: Optional[IdentityStrategy] = None
            if is_identity:
                if generated == _GEN_ALWAYS:
                    identity_gen = IdentityStrategy.ALWAYS
                elif generated == _GEN_BY_DEFAULT:
                    identity_gen = IdentityStrategy.BY_DEFAULT
                else:
                    identity_gen = IdentityStrategy.NONE

            columns.append(
                ColumnMetadata(
                    name=_lc(colname),
                    data_type=str(typename).strip().lower(),
                    max_length=int(length) if length else None,
                    numeric_precision=int(length) if typename in (
                        "DECIMAL", "NUMERIC", "FLOAT", "DOUBLE",
                    ) else None,
                    numeric_scale=int(scale) if scale is not None else None,
                    is_nullable=(nulls == "Y"),
                    is_identity=is_identity,
                    identity_generation=identity_gen,
                    default_value=str(default_val).strip() if default_val else None,
                    ordinal_position=int(colno),
                )
            )
        cursor.close()
        return columns

    def get_primary_key(self, table_name: str) -> Optional[PrimaryKeyMetadata]:
        """Return PK metadata from ``SYSCAT.TABCONST`` + ``SYSCAT.KEYCOLUSE``."""
        cursor = self.execute(
            "SELECT tc.CONSTNAME, kcu.COLNAME, kcu.COLSEQ "
            "FROM SYSCAT.TABCONST tc "
            "JOIN SYSCAT.KEYCOLUSE kcu "
            "  ON kcu.CONSTNAME = tc.CONSTNAME AND kcu.TABSCHEMA = tc.TABSCHEMA "
            "     AND kcu.TABNAME = tc.TABNAME "
            "WHERE tc.TABSCHEMA = ? AND tc.TABNAME = ? AND tc.TYPE = 'P' "
            "ORDER BY kcu.COLSEQ",
            (_uc(self.schema), _uc(table_name)),
        )
        rows = cursor.fetchall()
        cursor.close()
        if not rows:
            return None
        constraint_name = _lc(rows[0][0])
        pk_columns = [_lc(r[1]) for r in rows]
        return PrimaryKeyMetadata(
            columns=pk_columns,
            constraint_name=constraint_name,
        )

    def get_foreign_keys(self, table_name: str) -> list[ForeignKeyMetadata]:
        """Return FK metadata from ``SYSCAT.REFERENCES`` + ``SYSCAT.KEYCOLUSE``."""
        cursor = self.execute(
            "SELECT r.CONSTNAME, r.REFTABSCHEMA, r.REFTABNAME, r.REFKEYNAME "
            "FROM SYSCAT.REFERENCES r "
            "WHERE r.TABSCHEMA = ? AND r.TABNAME = ? "
            "ORDER BY r.CONSTNAME",
            (_uc(self.schema), _uc(table_name)),
        )
        ref_rows = cursor.fetchall()
        cursor.close()
        if not ref_rows:
            return []

        fks: list[ForeignKeyMetadata] = []
        for constname, ref_schema, ref_table, ref_key_name in ref_rows:
            # FK columns
            cur = self.execute(
                "SELECT COLNAME FROM SYSCAT.KEYCOLUSE "
                "WHERE TABSCHEMA = ? AND TABNAME = ? AND CONSTNAME = ? "
                "ORDER BY COLSEQ",
                (_uc(self.schema), _uc(table_name), constname),
            )
            fk_cols = [_lc(r[0]) for r in cur.fetchall()]
            cur.close()

            # Referenced columns (via the referenced constraint)
            cur = self.execute(
                "SELECT COLNAME FROM SYSCAT.KEYCOLUSE "
                "WHERE TABSCHEMA = ? AND TABNAME = ? AND CONSTNAME = ? "
                "ORDER BY COLSEQ",
                (ref_schema, ref_table, ref_key_name),
            )
            ref_cols = [_lc(r[0]) for r in cur.fetchall()]
            cur.close()

            fks.append(
                ForeignKeyMetadata(
                    constraint_name=_lc(constname),
                    columns=fk_cols,
                    referenced_table=_lc(ref_table),
                    referenced_columns=ref_cols,
                    referenced_schema=_lc(ref_schema) if ref_schema else None,
                )
            )
        return fks

    def get_identity_columns(self, table_name: str) -> list[ColumnMetadata]:
        """Return columns where ``IDENTITY = 'Y'``."""
        all_cols = self.get_columns(table_name)
        return [c for c in all_cols if c.is_identity]

    def get_sequences(self) -> list[SequenceMetadata]:
        """Return sequences from ``SYSCAT.SEQUENCES``.

        Both standalone sequences and identity sequences are returned;
        identity sequences have ``SEQTYPE = 'I'`` and are linked to their
        owning table/column via ``SYSCAT.COLIDENTATTRIBUTES.SEQID``.
        """
        cursor = self.execute(
            "SELECT s.SEQNAME, s.SEQTYPE, s.START, s.INCREMENT, s.CACHE, "
            "       s.NEXTCACHEFIRSTVALUE, cia.TABNAME, cia.COLNAME "
            "FROM SYSCAT.SEQUENCES s "
            "LEFT JOIN SYSCAT.COLIDENTATTRIBUTES cia "
            "    ON cia.SEQID = s.SEQID AND cia.TABSCHEMA = s.SEQSCHEMA "
            "WHERE s.SEQSCHEMA = ? "
            "ORDER BY s.SEQNAME",
            (_uc(self.schema),),
        )
        sequences: list[SequenceMetadata] = []
        for row in cursor.fetchall():
            seqname, seqtype, start, incr, cache, nextval, tabname, colname = row
            sequences.append(
                SequenceMetadata(
                    name=_lc(seqname),
                    start_value=int(start) if start is not None else 1,
                    increment=int(incr) if incr is not None else 1,
                    cache_size=int(cache) if cache is not None else 1,
                    last_value=int(nextval) if nextval is not None else None,
                    is_identity_sequence=(seqtype == "I"),
                    associated_table=_lc(tabname) if tabname else None,
                    associated_column=_lc(colname) if colname else None,
                )
            )
        cursor.close()
        return sequences

    def get_triggers(self, table_name: str) -> list[TriggerMetadata]:
        """Return trigger metadata from ``SYSCAT.TRIGGERS``."""
        cursor = self.execute(
            "SELECT TRIGNAME, TRIGEVENT, TRIGTIME, TEXT "
            "FROM SYSCAT.TRIGGERS "
            "WHERE TABSCHEMA = ? AND TABNAME = ? "
            "ORDER BY TRIGNAME",
            (_uc(self.schema), _uc(table_name)),
        )
        triggers: list[TriggerMetadata] = []
        for row in cursor.fetchall():
            name, event, timing, body = row
            triggers.append(
                TriggerMetadata(
                    name=_lc(name),
                    table_name=_lc(table_name),
                    event=_TRIG_EVENT_MAP.get(event, event),
                    timing=_TRIG_TIME_MAP.get(timing, timing),
                    body=str(body) if body else None,
                )
            )
        cursor.close()
        return triggers

    def get_row_count(self, table_name: str) -> int:
        """Return exact row count via ``SELECT COUNT(*)``."""
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        cursor = self.execute(f"SELECT COUNT(*) FROM {fqn}")  # noqa: S608
        count = cursor.fetchone()[0]
        cursor.close()
        return int(count)

    def get_max_primary_key(self, table_name: str, pk_column: str) -> Optional[int]:
        """Return ``MAX(pk_column)`` or ``None`` if the table is empty."""
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        cursor = self.execute(
            f"SELECT MAX({_uc(pk_column)}) FROM {fqn}"  # noqa: S608
        )
        row = cursor.fetchone()
        cursor.close()
        if row is None or row[0] is None:
            return None
        return int(row[0])

    # ---- data access ------------------------------------------------------

    def stream_rows(
        self,
        table_name: str,
        columns: list[str],
        pk_column: Optional[str] = None,
        start_pk: Optional[int] = None,
        end_pk: Optional[int] = None,
        batch_size: int = _DEFAULT_FETCH_SIZE,
    ) -> Generator[list[dict[str, Any]], None, None]:
        """Yield rows in batches via ``cursor.fetchmany``.

        DB2's ``ibm_db_dbi`` does not support true named server-side cursors,
        so we stream by fetching *batch_size* rows at a time.  When a PK
        column is supplied, keyset pagination is used for deterministic
        ordering and optional range filtering.
        """
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        col_list = ", ".join(_uc(c) for c in columns)

        where_parts: list[str] = []
        params: list[Any] = []

        if pk_column is not None:
            if start_pk is not None:
                where_parts.append(f"{_uc(pk_column)} >= ?")
                params.append(start_pk)
            if end_pk is not None:
                where_parts.append(f"{_uc(pk_column)} <= ?")
                params.append(end_pk)

        where_clause = f" WHERE {' AND '.join(where_parts)}" if where_parts else ""
        order_clause = f" ORDER BY {_uc(pk_column)}" if pk_column else ""

        sql = f"SELECT {col_list} FROM {fqn}{where_clause}{order_clause}"  # noqa: S608
        conn = self._ensure_connected()
        cursor = conn.cursor()
        try:
            cursor.execute(sql, tuple(params) if params else None)
            col_names = [_lc(c) for c in columns]
            while True:
                rows = cursor.fetchmany(batch_size)
                if not rows:
                    break
                batch = [
                    dict(zip(col_names, self._normalise_row(row)))
                    for row in rows
                ]
                yield batch
        finally:
            cursor.close()

    def fetch_rows_by_keys(
        self,
        table_name: str,
        columns: list[str],
        pk_column: str,
        pk_values: list[Any],
    ) -> list[dict[str, Any]]:
        """Fetch specific rows by primary key values."""
        if not pk_values:
            return []
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        col_list = ", ".join(_uc(c) for c in columns)
        placeholders = ", ".join("?" for _ in pk_values)
        sql = (
            f"SELECT {col_list} FROM {fqn} "  # noqa: S608
            f"WHERE {_uc(pk_column)} IN ({placeholders})"
        )
        conn = self._ensure_connected()
        cursor = conn.cursor()
        try:
            cursor.execute(sql, tuple(pk_values))
            col_names = [_lc(c) for c in columns]
            return [
                dict(zip(col_names, self._normalise_row(row)))
                for row in cursor.fetchall()
            ]
        finally:
            cursor.close()

    def stream_primary_keys(
        self,
        table_name: str,
        pk_column: str,
        batch_size: int = 10000,
    ) -> Generator[list[int], None, None]:
        """Yield sorted primary-key values in batches for delta comparison."""
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        sql = f"SELECT {_uc(pk_column)} FROM {fqn} ORDER BY {_uc(pk_column)}"  # noqa: S608
        conn = self._ensure_connected()
        cursor = conn.cursor()
        try:
            cursor.execute(sql)
            while True:
                rows = cursor.fetchmany(batch_size)
                if not rows:
                    break
                yield [int(r[0]) for r in rows]
        finally:
            cursor.close()

    # ---- data mutation ----------------------------------------------------

    def insert_batch(
        self,
        table_name: str,
        columns: list[str],
        rows: list[tuple[Any, ...]],
        identity_strategy: IdentityStrategy = IdentityStrategy.NONE,
    ) -> int:
        """Insert rows, handling identity column generation rules.

        For ``GENERATED ALWAYS`` columns, the identity generation is
        temporarily switched to ``BY DEFAULT`` before the insert and restored
        afterwards.
        """
        if not rows:
            return 0

        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        col_list = ", ".join(_uc(c) for c in columns)
        placeholders = ", ".join("?" for _ in columns)
        sql = f"INSERT INTO {fqn} ({col_list}) VALUES ({placeholders})"

        altered = False
        identity_col: Optional[str] = None

        if identity_strategy == IdentityStrategy.ALWAYS:
            # Must ALTER to BY DEFAULT to allow explicit id values.
            identity_cols = self.get_identity_columns(table_name)
            if identity_cols:
                identity_col = identity_cols[0].name
                self._set_identity_generated(table_name, identity_col, "BY DEFAULT")
                altered = True

        try:
            count = self.execute_many(sql, rows)
            return count
        finally:
            if altered and identity_col is not None:
                self._set_identity_generated(table_name, identity_col, "ALWAYS")

    def update_batch(
        self,
        table_name: str,
        pk_columns: list[str],
        update_columns: list[str],
        rows: list[tuple[Any, ...]],
    ) -> int:
        """Update rows by primary key.

        Each row tuple must contain update-column values followed by PK values
        in the order ``(*update_values, *pk_values)``.
        """
        if not rows:
            return 0
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        set_clause = ", ".join(f"{_uc(c)} = ?" for c in update_columns)
        where_clause = " AND ".join(f"{_uc(c)} = ?" for c in pk_columns)
        sql = f"UPDATE {fqn} SET {set_clause} WHERE {where_clause}"
        return self.execute_many(sql, rows)

    def delete_batch(
        self,
        table_name: str,
        pk_columns: list[str],
        pk_values: list[tuple[Any, ...]],
    ) -> int:
        """Delete rows by primary key."""
        if not pk_values:
            return 0
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        where_clause = " AND ".join(f"{_uc(c)} = ?" for c in pk_columns)
        sql = f"DELETE FROM {fqn} WHERE {where_clause}"
        return self.execute_many(sql, pk_values)

    # ---- bulk load --------------------------------------------------------

    def supports_bulk_load(self) -> bool:
        """DB2 supports bulk load via LOAD utility or ALTER identity fallback."""
        return True

    def bulk_load(
        self,
        table_name: str,
        file_path: str,
        columns: list[str],
        identity_override: bool = False,
    ) -> int:
        """Bulk-load a DEL (CSV) file into *table_name*.

        Strategy selection
        ~~~~~~~~~~~~~~~~~~
        * **``use_load_utility=True``** (set at construction): invokes the
          ``db2`` CLI with ``LOAD FROM <file> OF DEL MODIFIED BY
          IDENTITYOVERRIDE INSERT INTO <table>``.  This is the fastest path
          but requires CLI access on the DB2 host.
        * **``use_load_utility=False``** (default): uses standard INSERT
          with the ``ALTER COLUMN ... SET GENERATED BY DEFAULT`` workaround
          for ``GENERATED ALWAYS`` columns.

        Returns the number of rows loaded.
        """
        if self._use_load_utility:
            return self._bulk_load_via_cli(table_name, file_path, columns, identity_override)
        return self._bulk_load_via_insert(table_name, file_path, columns, identity_override)

    def _bulk_load_via_cli(
        self,
        table_name: str,
        file_path: str,
        columns: list[str],
        identity_override: bool,
    ) -> int:
        """Execute bulk load using the ``db2`` CLI LOAD command.

        The LOAD utility runs on the DB2 server and is the most efficient
        path.  Requires ``db2`` to be available on ``$PATH``.

        Command issued::

            db2 "LOAD FROM '<file_path>' OF DEL
                 MODIFIED BY IDENTITYOVERRIDE COLDEL,
                 INSERT INTO <schema>.<table> (<columns>)"
        """
        fqn = f"{_uc(self.schema)}.{_uc(table_name)}"
        col_list = ", ".join(_uc(c) for c in columns)
        modified_by = "IDENTITYOVERRIDE COLDEL," if identity_override else "COLDEL,"
        load_sql = (
            f"LOAD FROM '{file_path}' OF DEL "
            f"MODIFIED BY {modified_by} "
            f"INSERT INTO {fqn} ({col_list})"
        )

        logger.info("Executing DB2 LOAD: %s", load_sql)
        try:
            result = subprocess.run(
                ["db2", load_sql],
                capture_output=True,
                text=True,
                timeout=3600,
                check=False,
            )
            if result.returncode not in (0, 2):  # 2 = warnings
                raise RuntimeError(
                    f"DB2 LOAD failed (rc={result.returncode}): "
                    f"{result.stderr or result.stdout}"
                )
            # Parse rows loaded from stdout.  LOAD output contains a line
            # like "Number of rows read         = 12345".
            loaded = 0
            for line in result.stdout.splitlines():
                if "rows loaded" in line.lower():
                    parts = line.split("=")
                    if len(parts) == 2:
                        loaded = int(parts[1].strip())
                        break
            logger.info("DB2 LOAD completed: %d rows loaded.", loaded)
            return loaded
        except FileNotFoundError:
            raise RuntimeError(
                "db2 CLI not found on PATH.  Set use_load_utility=False "
                "to use the ALTER COLUMN identity override approach."
            ) from None

    def _bulk_load_via_insert(
        self,
        table_name: str,
        file_path: str,
        columns: list[str],
        identity_override: bool,
    ) -> int:
        """Fallback bulk load: read the DEL file and batch-INSERT.

        For ``GENERATED ALWAYS`` columns, temporarily alters the identity
        generation to ``BY DEFAULT``.
        """
        import csv

        identity_col: Optional[str] = None
        altered = False
        if identity_override:
            id_cols = self.get_identity_columns(table_name)
            always_cols = [
                c for c in id_cols
                if c.identity_generation == IdentityStrategy.ALWAYS
            ]
            if always_cols:
                identity_col = always_cols[0].name
                self._set_identity_generated(table_name, identity_col, "BY DEFAULT")
                altered = True

        total = 0
        batch: list[tuple[Any, ...]] = []
        batch_size = _DEFAULT_FETCH_SIZE

        try:
            with open(file_path, newline="", encoding="utf-8") as fh:
                reader = csv.reader(fh)
                for csv_row in reader:
                    batch.append(tuple(csv_row))
                    if len(batch) >= batch_size:
                        total += self.insert_batch(
                            table_name, columns, batch, IdentityStrategy.NONE,
                        )
                        self.commit()
                        batch.clear()
                if batch:
                    total += self.insert_batch(
                        table_name, columns, batch, IdentityStrategy.NONE,
                    )
                    self.commit()
            logger.info("Bulk load via INSERT completed: %d rows.", total)
            return total
        finally:
            if altered and identity_col is not None:
                self._set_identity_generated(table_name, identity_col, "ALWAYS")

    # ---- trigger management -----------------------------------------------

    def disable_triggers(self, table_name: str) -> None:
        """Disable all triggers on *table_name*.

        DB2 uses ``ALTER TABLE ... ALTER TRIGGER ... SET NOT ACTIVE``.
        """
        triggers = self.get_triggers(table_name)
        for trig in triggers:
            sql = (
                f"ALTER TABLE {_uc(self.schema)}.{_uc(table_name)} "
                f"ALTER TRIGGER {_uc(trig.name)} SET NOT ACTIVE"
            )
            logger.debug("Disabling trigger: %s", trig.name)
            self.execute(sql)
        if triggers:
            self.commit()

    def enable_triggers(self, table_name: str) -> None:
        """Re-enable all triggers on *table_name*."""
        triggers = self.get_triggers(table_name)
        for trig in triggers:
            sql = (
                f"ALTER TABLE {_uc(self.schema)}.{_uc(table_name)} "
                f"ALTER TRIGGER {_uc(trig.name)} SET ACTIVE"
            )
            logger.debug("Enabling trigger: %s", trig.name)
            self.execute(sql)
        if triggers:
            self.commit()

    # ---- identity management ----------------------------------------------

    def reset_identity(self, table_name: str, column_name: str, new_value: int) -> None:
        """Restart the identity column's internal counter.

        Issues ``ALTER TABLE ... ALTER COLUMN ... RESTART WITH <value>``.
        """
        sql = (
            f"ALTER TABLE {_uc(self.schema)}.{_uc(table_name)} "
            f"ALTER COLUMN {_uc(column_name)} RESTART WITH {int(new_value)}"
        )
        logger.info("Resetting identity: %s.%s to %d", table_name, column_name, new_value)
        self.execute(sql)
        self.commit()

    def reset_sequence(self, sequence_name: str, new_value: int) -> None:
        """Restart a standalone sequence.

        Issues ``ALTER SEQUENCE <schema>.<name> RESTART WITH <value>``.
        """
        sql = (
            f"ALTER SEQUENCE {_uc(self.schema)}.{_uc(sequence_name)} "
            f"RESTART WITH {int(new_value)}"
        )
        logger.info("Resetting sequence %s to %d", sequence_name, new_value)
        self.execute(sql)
        self.commit()

    # ---- internal helpers -------------------------------------------------

    def _set_identity_generated(
        self,
        table_name: str,
        column_name: str,
        mode: str,
    ) -> None:
        """ALTER identity generation mode (``ALWAYS`` or ``BY DEFAULT``).

        Used to temporarily allow explicit inserts into ``GENERATED ALWAYS``
        identity columns.
        """
        sql = (
            f"ALTER TABLE {_uc(self.schema)}.{_uc(table_name)} "
            f"ALTER COLUMN {_uc(column_name)} SET GENERATED {mode}"
        )
        logger.info("Setting identity generation for %s.%s to %s", table_name, column_name, mode)
        self.execute(sql)
        self.commit()

    @staticmethod
    def _normalise_row(row: tuple[Any, ...]) -> tuple[Any, ...]:
        """Normalise CLOB / XML / memoryview values to plain strings/bytes.

        ``ibm_db_dbi`` may return LOB locators or memoryview objects for
        CLOB/BLOB/XML columns; we read them eagerly into Python strings.
        """
        normalised: list[Any] = []
        for val in row:
            if val is None:
                normalised.append(None)
            elif isinstance(val, memoryview):
                normalised.append(bytes(val))
            elif hasattr(val, "read"):
                # LOB locator — read full content
                normalised.append(val.read())
            else:
                normalised.append(val)
        return tuple(normalised)
