"""Schema creation and data population for Db2 and PostgreSQL containers.

This module generates DDL for both engines from a shared table definition,
handles type mapping differences, and provides batched insert logic with
verification.

Type mapping notes (Db2 → PostgreSQL):
  ┌─────────────────┬────────────────────┬──────────────────────────────┐
  │ Db2 Type        │ PostgreSQL Type    │ Notes                        │
  ├─────────────────┼────────────────────┼──────────────────────────────┤
  │ BIGINT          │ BIGINT             │ Identical                    │
  │ INTEGER         │ INTEGER            │ Identical                    │
  │ SMALLINT        │ SMALLINT           │ Identical                    │
  │ VARCHAR(n)      │ VARCHAR(n)         │ Identical                    │
  │ CLOB            │ TEXT               │ PG uses TEXT, no length      │
  │ BLOB            │ BYTEA              │ Binary storage differs       │
  │ DECIMAL(p,s)    │ NUMERIC(p,s)       │ Functionally equivalent      │
  │ DATE            │ DATE               │ Identical                    │
  │ TIMESTAMP       │ TIMESTAMP          │ Identical                    │
  │ XML             │ XML                │ PG supports native XML       │
  └─────────────────┴────────────────────┴──────────────────────────────┘
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

logger = logging.getLogger(__name__)


class Engine(str, Enum):
    DB2 = "db2"
    POSTGRES = "postgres"


@dataclass
class ColumnDef:
    """Definition of a single column, engine-agnostic."""

    name: str
    db2_type: str
    pg_type: str
    nullable: bool = True
    is_identity: bool = False
    # For identity columns: Db2 uses GENERATED BY DEFAULT AS IDENTITY,
    # PG uses GENERATED BY DEFAULT AS IDENTITY or SERIAL/BIGSERIAL.


@dataclass
class TableDef:
    """Engine-agnostic table definition."""

    name: str
    schema_name: str
    columns: list[ColumnDef]
    primary_key: list[str]  # column names forming the PK
    has_identity: bool = False


# ── Table definitions (from WEALTHADAPTER schema analysis) ───────────────

TABLES: list[TableDef] = [
    # 1. userrole (independent)
    TableDef(
        name="userrole",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("role", "VARCHAR(50)", "VARCHAR(50)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 2. wealthaccessright (independent)
    TableDef(
        name="wealthaccessright",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("name", "VARCHAR(50)", "VARCHAR(50)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 3. role_accessright (depends on userrole, wealthaccessright)
    TableDef(
        name="role_accessright",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("role_id", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("accessright_id", "BIGINT", "BIGINT", nullable=False),
        ],
        primary_key=["role_id", "accessright_id"],
    ),
    # 4. adapterconfig (independent)
    TableDef(
        name="adapterconfig",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("key", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("value", "VARCHAR(3700)", "VARCHAR(3700)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 5. emailgroup (independent)
    TableDef(
        name="emailgroup",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("name", "VARCHAR(255)", "VARCHAR(255)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 6. recipient (independent)
    TableDef(
        name="recipient",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("name", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("sysid", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("replyto", "VARCHAR(255)", "VARCHAR(255)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 7. directorylocation (independent)
    TableDef(
        name="directorylocation",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("dir", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("filemask", "VARCHAR(255)", "VARCHAR(255)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 8. emailaddress (depends on emailgroup via emailgroup_fk)
    TableDef(
        name="emailaddress",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("description", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("emailaddress", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("emailgroup_fk", "BIGINT", "BIGINT"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 9. emailgroup_emailaddress (depends on emailgroup, emailaddress)
    TableDef(
        name="emailgroup_emailaddress",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("emailgroup_id", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("emailaddresses_id", "BIGINT", "BIGINT", nullable=False),
        ],
        primary_key=["emailgroup_id", "emailaddresses_id"],
    ),
    # 10. recipient_dirlocations (depends on recipient, directorylocation)
    TableDef(
        name="recipient_dirlocations",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("recipients_id", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("directorylocations_id", "BIGINT", "BIGINT", nullable=False),
        ],
        primary_key=["recipients_id", "directorylocations_id"],
    ),
    # 11. recipient_emailgroup (depends on recipient, emailgroup)
    TableDef(
        name="recipient_emailgroup",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("recipients_id", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("emailgroups_id", "BIGINT", "BIGINT", nullable=False),
        ],
        primary_key=["recipients_id", "emailgroups_id"],
    ),
    # 12. webservice (independent, NO identity)
    TableDef(
        name="webservice",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("type", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("username", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("password", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("companycode", "VARCHAR(255)", "VARCHAR(255)"),
        ],
        primary_key=["id"],
        has_identity=False,
    ),
    # 13. recipient_webservices (depends on recipient, webservice)
    TableDef(
        name="recipient_webservices",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("recipients_id", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("webservice_id", "BIGINT", "BIGINT", nullable=False),
        ],
        primary_key=["recipients_id", "webservice_id"],
    ),
    # 14. userdetail (independent)
    TableDef(
        name="userdetail",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("datepasswordchanged", "DATE", "DATE"),
            ColumnDef("email", "VARCHAR(50)", "VARCHAR(50)"),
            ColumnDef("personnelnumber", "VARCHAR(50)", "VARCHAR(50)"),
            ColumnDef("surname", "VARCHAR(50)", "VARCHAR(50)"),
            ColumnDef("telephonenumber", "VARCHAR(20)", "VARCHAR(20)"),
            ColumnDef("uid", "VARCHAR(50)", "VARCHAR(50)", nullable=False),
            ColumnDef("username", "VARCHAR(50)", "VARCHAR(50)"),
            ColumnDef("domain_user", "VARCHAR(50)", "VARCHAR(50)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 15. facsmessageentity (independent)
    TableDef(
        name="facsmessageentity",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("messageid", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("replyendpoint", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("requestmessage", "VARCHAR(700)", "VARCHAR(700)"),
            ColumnDef("responsemessage", "VARCHAR(700)", "VARCHAR(700)"),
            ColumnDef("status", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("facskey", "VARCHAR(30)", "VARCHAR(30)"),
            ColumnDef("transformfromtransactioncode", "VARCHAR(5)", "VARCHAR(5)"),
            ColumnDef("transformtotransactioncode", "VARCHAR(5)", "VARCHAR(5)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 16. facsmessagehistoryitementity (depends on facsmessageentity)
    TableDef(
        name="facsmessagehistoryitementity",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("created", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("description", "VARCHAR(1000)", "VARCHAR(1000)"),
            ColumnDef("status", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("facsmessage_id", "BIGINT", "BIGINT"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 17. jmssystemadaptermessage (independent)
    TableDef(
        name="jmssystemadaptermessage",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("callerreferencetype", "VARCHAR(40)", "VARCHAR(40)"),
            ColumnDef("messageid", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("remotereference", "VARCHAR(25)", "VARCHAR(25)"),
            ColumnDef("replyendpoint", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("requestmessage", "VARCHAR(3500)", "VARCHAR(3500)"),
            ColumnDef("responsemessage", "VARCHAR(3000)", "VARCHAR(3000)"),
            ColumnDef("status", "VARCHAR(25)", "VARCHAR(25)"),
            ColumnDef("type", "VARCHAR(25)", "VARCHAR(25)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 18. jmssystemadaptermessagestatus (depends on jmssystemadaptermessage)
    TableDef(
        name="jmssystemadaptermessagestatus",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("created", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("description", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("status", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("message_id", "BIGINT", "BIGINT"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 19. gicsawasyncmessage (independent)
    TableDef(
        name="gicsawasyncmessage",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("alsoscan", "SMALLINT", "SMALLINT"),
            ColumnDef("callbackurl", "VARCHAR(150)", "VARCHAR(150)"),
            ColumnDef("callerreference", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("callerreferencetype", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("dispatchtype", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("errormessage", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("gicsawcorrelationid", "VARCHAR(100)", "VARCHAR(100)"),
            ColumnDef("lastupdatedate", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("requestmessage", "CLOB", "TEXT"),
            ColumnDef("responsemessage", "VARCHAR(1000)", "VARCHAR(1000)"),
            ColumnDef("responsereceiveddate", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("status", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("statusmessage", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("parentcrda", "VARCHAR(30)", "VARCHAR(30)"),
            ColumnDef("parentrec", "VARCHAR(5)", "VARCHAR(5)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 20. incomingfile (independent)
    TableDef(
        name="incomingfile",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("file_type", "VARCHAR(1000)", "VARCHAR(1000)"),
            ColumnDef("file_date", "VARCHAR(100)", "VARCHAR(100)"),
            ColumnDef("file_name", "VARCHAR(1000)", "VARCHAR(1000)"),
            ColumnDef("document_id", "VARCHAR(500)", "VARCHAR(500)"),
            ColumnDef("file_hash", "VARCHAR(500)", "VARCHAR(500)"),
            ColumnDef("status", "VARCHAR(50)", "VARCHAR(50)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 21. outboundemail (independent)
    TableDef(
        name="outboundemail",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("created_at", "TIMESTAMP", "TIMESTAMP", nullable=False),
            ColumnDef("dispatched_at", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("xmlcontent", "VARCHAR(32000)", "TEXT", nullable=False),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 22. remote_interaction_log (independent)
    TableDef(
        name="remote_interaction_log",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("interaction_medium", "VARCHAR(200)", "VARCHAR(200)"),
            ColumnDef("service_uri", "VARCHAR(400)", "VARCHAR(400)"),
            ColumnDef("service_method", "VARCHAR(200)", "VARCHAR(200)"),
            ColumnDef("user_principal", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("started_at", "TIMESTAMP", "TIMESTAMP", nullable=False),
            ColumnDef("completed_at", "TIMESTAMP", "TIMESTAMP", nullable=False),
            ColumnDef("duration_milliseconds", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("input", "CLOB", "TEXT"),
            ColumnDef("output", "CLOB", "TEXT"),
            ColumnDef("error", "CLOB", "TEXT"),
            ColumnDef("timeslot", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("batch_id", "BIGINT", "BIGINT"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 23. smsmessagelog (independent)
    TableDef(
        name="smsmessagelog",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("channel", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("messageid", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("idnumber", "VARCHAR(13)", "VARCHAR(13)"),
            ColumnDef("message", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("sendernumber", "VARCHAR(11)", "VARCHAR(11)"),
            ColumnDef("recipientnumber", "VARCHAR(11)", "VARCHAR(11)"),
            ColumnDef("messagereceivedtimestamp", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("messagesenttimestamp", "VARCHAR(26)", "VARCHAR(26)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 24. systemstatuslog (independent)
    TableDef(
        name="systemstatuslog",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("action", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("hostname", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("status", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("statusmessage", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("systemname", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("timestamp", "TIMESTAMP", "TIMESTAMP"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 25. voc_message_log (independent)
    TableDef(
        name="voc_message_log",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("request_id", "BIGINT", "BIGINT", nullable=False),
            ColumnDef("processed_at", "TIMESTAMP", "TIMESTAMP", nullable=False),
            ColumnDef("voc_event", "VARCHAR(50)", "VARCHAR(50)", nullable=False),
            ColumnDef("activities", "CLOB", "TEXT"),
            ColumnDef("voc_message", "VARCHAR(32000)", "TEXT"),
            ColumnDef("reason_not_dispatched", "VARCHAR(250)", "VARCHAR(250)"),
            ColumnDef("exception", "CLOB", "TEXT"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
    # 26. webservicestatusmessage (independent)
    TableDef(
        name="webservicestatusmessage",
        schema_name="wealthadapter",
        columns=[
            ColumnDef("id", "BIGINT", "BIGINT", nullable=False, is_identity=True),
            ColumnDef("refno", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("createddate", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("lastupdatedate", "TIMESTAMP", "TIMESTAMP"),
            ColumnDef("filename", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("username", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("password", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("statustype", "VARCHAR(255)", "VARCHAR(255)"),
            ColumnDef("statusmessage", "VARCHAR(5000)", "VARCHAR(5000)"),
            ColumnDef("type", "VARCHAR(255)", "VARCHAR(255)"),
        ],
        primary_key=["id"],
        has_identity=True,
    ),
]

TABLE_INDEX: dict[str, TableDef] = {t.name: t for t in TABLES}


# ── Helpers ──────────────────────────────────────────────────────────────


def _qualified_name(table: TableDef) -> str:
    """Return schema-qualified table name: "schema"."table"."""
    return f'"{table.schema_name}"."{table.name}"'


# ── DDL Generation ───────────────────────────────────────────────────────


def _col_ddl(col: ColumnDef, engine: Engine) -> str:
    """Generate column DDL fragment for the given engine."""
    dtype = col.db2_type if engine == Engine.DB2 else col.pg_type
    parts = [f'"{col.name}" {dtype}']

    if not col.nullable:
        parts.append("NOT NULL")

    if col.is_identity:
        if engine == Engine.DB2:
            parts.append("GENERATED BY DEFAULT AS IDENTITY")
        else:
            parts.append("GENERATED BY DEFAULT AS IDENTITY")

    return " ".join(parts)


def generate_create_schema(schema_name: str, engine: Engine) -> str:
    """Generate CREATE SCHEMA DDL (idempotent).

    PostgreSQL: CREATE SCHEMA IF NOT EXISTS "schema";
    Db2:        CREATE SCHEMA "SCHEMA" (uppercase, ignore SQLSTATE 42710).
    """
    if engine == Engine.POSTGRES:
        return f'CREATE SCHEMA IF NOT EXISTS "{schema_name}";'
    else:
        # Db2 schemas are uppercase
        upper_schema = schema_name.upper()
        return (
            f"BEGIN\n"
            f"  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710'\n"
            f"    BEGIN END;\n"
            f"  EXECUTE IMMEDIATE 'CREATE SCHEMA \"{upper_schema}\"';\n"
            f"END"
        )


def generate_create_table(table: TableDef, engine: Engine) -> str:
    """Generate CREATE TABLE IF NOT EXISTS DDL with schema-qualified name.

    Db2 does not natively support IF NOT EXISTS on CREATE TABLE,
    so we wrap it in a BEGIN ATOMIC block that catches -601 (table exists).
    PostgreSQL supports IF NOT EXISTS directly.
    """
    col_lines = [_col_ddl(c, engine) for c in table.columns]

    pk_cols = ", ".join(f'"{c}"' for c in table.primary_key)
    col_lines.append(f"PRIMARY KEY ({pk_cols})")

    columns_sql = ",\n    ".join(col_lines)

    if engine == Engine.POSTGRES:
        qname = _qualified_name(table)
        return (
            f"CREATE TABLE IF NOT EXISTS {qname} (\n"
            f"    {columns_sql}\n"
            f");"
        )
    else:
        # Db2: schema names are uppercase
        db2_qname = f'"{table.schema_name.upper()}"."{table.name}"'
        inner_ddl = (
            f"CREATE TABLE {db2_qname} (\n"
            f"    {columns_sql}\n"
            f")"
        )
        return (
            f"BEGIN\n"
            f"  DECLARE CONTINUE HANDLER FOR SQLSTATE '42710'\n"
            f"    BEGIN END;\n"
            f"  EXECUTE IMMEDIATE '{inner_ddl.replace(chr(39), chr(39)+chr(39))}';\n"
            f"END"
        )


def generate_all_ddl(engine: Engine) -> list[str]:
    """Return ordered CREATE TABLE statements for all tables."""
    # Collect distinct schemas and generate CREATE SCHEMA first
    schemas_seen: set[str] = set()
    stmts: list[str] = []
    for t in TABLES:
        if t.schema_name not in schemas_seen:
            stmts.append(generate_create_schema(t.schema_name, engine))
            schemas_seen.add(t.schema_name)
    stmts.extend(generate_create_table(t, engine) for t in TABLES)
    return stmts


# ── Data insertion ───────────────────────────────────────────────────────

BATCH_SIZE = 100


def _build_insert_sql(table: TableDef, engine: Engine) -> str:
    """Build a parameterised INSERT statement with schema-qualified name."""
    col_names = ", ".join(f'"{c.name}"' for c in table.columns)

    if engine == Engine.POSTGRES:
        placeholders = ", ".join(f"%s" for _ in table.columns)
        qname = _qualified_name(table)
    else:
        # ibm_db uses ? placeholders
        placeholders = ", ".join("?" for _ in table.columns)
        qname = f'"{table.schema_name.upper()}"."{table.name}"'

    return f'INSERT INTO {qname} ({col_names}) VALUES ({placeholders})'


def _row_to_tuple(row: dict[str, Any], table: TableDef) -> tuple:
    """Extract column values from a row dict in table column order."""
    return tuple(row.get(c.name, None) for c in table.columns)


def insert_rows_postgres(
    conn: Any,
    table: TableDef,
    rows: list[dict[str, Any]],
) -> int:
    """Insert rows into PostgreSQL using batched executemany.

    If the table has an identity column, we temporarily set it to allow
    explicit values, then reset the sequence afterwards.
    """
    if not rows:
        return 0

    cur = conn.cursor()
    inserted = 0

    try:
        # For identity columns, allow explicit ID insertion
        qname = _qualified_name(table)
        if table.has_identity:
            cur.execute(
                f'ALTER TABLE {qname} '
                f'ALTER COLUMN "{table.primary_key[0]}" DROP IDENTITY'
            )
            conn.commit()

        sql = _build_insert_sql(table, Engine.POSTGRES)
        tuples = [_row_to_tuple(r, table) for r in rows]

        # Batch insert
        for i in range(0, len(tuples), BATCH_SIZE):
            batch = tuples[i : i + BATCH_SIZE]
            cur.executemany(sql, batch)
            conn.commit()
            inserted += len(batch)

        # Re-add identity and reset sequence
        if table.has_identity:
            pk_col = table.primary_key[0]
            cur.execute(
                f'ALTER TABLE {qname} '
                f'ALTER COLUMN "{pk_col}" ADD GENERATED BY DEFAULT AS IDENTITY'
            )
            # Set sequence to max(id) + 1
            cur.execute(
                f'SELECT COALESCE(MAX("{pk_col}"), 0) + 1 FROM {qname}'
            )
            next_val = cur.fetchone()[0]
            # Get the sequence name — pg_get_serial_sequence needs
            # schema-qualified table as a single string argument
            cur.execute(
                f"SELECT pg_get_serial_sequence('{table.schema_name}.{table.name}', '{pk_col}')"
            )
            seq_result = cur.fetchone()
            if seq_result and seq_result[0]:
                cur.execute(
                    f"ALTER SEQUENCE {seq_result[0]} RESTART WITH {next_val}"
                )
            conn.commit()

    except Exception:
        conn.rollback()
        raise
    finally:
        cur.close()

    return inserted


def insert_rows_db2(
    conn: Any,
    table: TableDef,
    rows: list[dict[str, Any]],
) -> int:
    """Insert rows into Db2 using batched ibm_db prepared statements.

    Identity columns require SET IDENTITY_INSERT before explicit values.
    """
    import ibm_db

    if not rows:
        return 0

    inserted = 0

    # Enable identity insert if needed
    if table.has_identity:
        db2_qname = f'"{table.schema_name.upper()}"."{table.name}"'
        try:
            ibm_db.exec_immediate(
                conn,
                f'ALTER TABLE {db2_qname} ALTER COLUMN "{table.primary_key[0]}" '
                f'SET GENERATED BY DEFAULT',
            )
        except Exception:
            pass  # May already be set

    sql = _build_insert_sql(table, Engine.DB2)
    stmt = ibm_db.prepare(conn, sql)

    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i : i + BATCH_SIZE]
        for row in batch:
            values = _row_to_tuple(row, table)
            for idx, val in enumerate(values, start=1):
                ibm_db.bind_param(stmt, idx, val)
            ibm_db.execute(stmt)
            inserted += 1

    return inserted


# ── Schema creation ──────────────────────────────────────────────────────


def create_schema_postgres(conn: Any) -> list[str]:
    """Create wealthadapter schema and all tables in PostgreSQL.

    Returns list of created table names.
    """
    cur = conn.cursor()
    created = []

    # Create schema first (idempotent)
    schemas_done: set[str] = set()
    for table in TABLES:
        if table.schema_name not in schemas_done:
            schema_ddl = generate_create_schema(table.schema_name, Engine.POSTGRES)
            logger.info("Creating PG schema: %s", table.schema_name)
            try:
                cur.execute(schema_ddl)
                conn.commit()
            except Exception as exc:
                conn.rollback()
                logger.error("Failed to create PG schema %s: %s", table.schema_name, exc)
            schemas_done.add(table.schema_name)

    for table in TABLES:
        ddl = generate_create_table(table, Engine.POSTGRES)
        logger.info("Creating PG table: %s.%s", table.schema_name, table.name)
        try:
            cur.execute(ddl)
            conn.commit()
            created.append(table.name)
        except Exception as exc:
            conn.rollback()
            logger.error("Failed to create PG table %s: %s", table.name, exc)
    cur.close()
    return created


def create_schema_db2(conn: Any) -> list[str]:
    """Create WEALTHADAPTER schema and all tables in Db2.

    Returns list of created table names.
    """
    import ibm_db

    created = []

    # Create schema first (idempotent)
    schemas_done: set[str] = set()
    for table in TABLES:
        if table.schema_name not in schemas_done:
            upper_schema = table.schema_name.upper()
            logger.info("Creating Db2 schema: %s", upper_schema)
            try:
                ibm_db.exec_immediate(conn, f'CREATE SCHEMA "{upper_schema}"')
            except Exception as exc:
                error_msg = str(exc)
                if "SQL0601N" in error_msg or "42710" in error_msg:
                    logger.info("  Schema %s already exists (idempotent).", upper_schema)
                else:
                    logger.error("Failed to create Db2 schema %s: %s", upper_schema, exc)
            schemas_done.add(table.schema_name)

    for table in TABLES:
        # Use schema-qualified CREATE TABLE for Db2
        db2_qname = f'"{table.schema_name.upper()}"."{table.name}"'
        col_lines = [_col_ddl(c, Engine.DB2) for c in table.columns]
        pk_cols = ", ".join(f'"{c}"' for c in table.primary_key)
        col_lines.append(f"PRIMARY KEY ({pk_cols})")
        columns_sql = ", ".join(col_lines)
        ddl = f'CREATE TABLE {db2_qname} ({columns_sql})'

        logger.info("Creating Db2 table: %s.%s", table.schema_name.upper(), table.name)
        try:
            ibm_db.exec_immediate(conn, ddl)
            created.append(table.name)
        except Exception as exc:
            error_msg = str(exc)
            if "SQL0601N" in error_msg or "42710" in error_msg:
                logger.info("  Table %s already exists (idempotent).", table.name)
                created.append(table.name)
            else:
                logger.error("Failed to create Db2 table %s: %s", table.name, exc)
    return created


# ── Verification ─────────────────────────────────────────────────────────


@dataclass
class VerificationResult:
    """Row count verification result for one table."""

    table_name: str
    source_count: int
    db2_count: int
    pg_count: int
    db2_match: bool
    pg_match: bool


def verify_row_counts_postgres(conn: Any) -> dict[str, int]:
    """Return row counts for all tables in PostgreSQL (schema-qualified)."""
    cur = conn.cursor()
    counts: dict[str, int] = {}
    for table in TABLES:
        try:
            qname = _qualified_name(table)
            cur.execute(f'SELECT COUNT(*) FROM {qname}')
            counts[table.name] = cur.fetchone()[0]
        except Exception:
            conn.rollback()
            counts[table.name] = -1
    cur.close()
    return counts


def verify_row_counts_db2(conn: Any) -> dict[str, int]:
    """Return row counts for all tables in Db2 (schema-qualified)."""
    import ibm_db

    counts: dict[str, int] = {}
    for table in TABLES:
        try:
            db2_qname = f'"{table.schema_name.upper()}"."{table.name}"'
            stmt = ibm_db.exec_immediate(
                conn, f'SELECT COUNT(*) AS cnt FROM {db2_qname}'
            )
            row = ibm_db.fetch_assoc(stmt)
            counts[table.name] = row["CNT"] if row else -1
        except Exception:
            counts[table.name] = -1
    return counts


def verify_all(
    source_counts: dict[str, int],
    db2_counts: dict[str, int],
    pg_counts: dict[str, int],
) -> list[VerificationResult]:
    """Compare source counts against both databases."""
    results = []
    for table in TABLES:
        src = source_counts.get(table.name, 0)
        db2 = db2_counts.get(table.name, -1)
        pg = pg_counts.get(table.name, -1)
        results.append(
            VerificationResult(
                table_name=table.name,
                source_count=src,
                db2_count=db2,
                pg_count=pg,
                db2_match=(db2 == src),
                pg_match=(pg == src),
            )
        )
    return results
